"""Embeddable asyncio agent core with optional model providers."""

from .models import ModelInfo, ModelCatalog
from ._version import __version__ as __version__
from .agent import Agent, AgentStateView, RunResult
from .cancellation import CancelToken
from .errors import (
    PiError,
    ConfigurationError,
    MessageValidationError,
    UnsupportedCapabilityError,
    ProviderProtocolError,
    AgentBusyError,
    AgentClosedError,
    InvalidContinuationError,
    ToolOutcomeUnknownError,
    CleanupTimeoutError,
    SubscriptionError,
    CandidateValidationError,
)
from .events import Event, EventListener, Unsubscribe, EventQueue, encode_event, decode_event
from .hooks import AgentConfigUpdate, Hooks, RunContext, TurnUpdate
from .limits import RunLimits
from .messages import (
    JsonValue,
    Message,
    TextContent,
    ImageContent,
    ThinkingContent,
    ToolCall,
    ToolDeclaration,
    SystemMessage,
    UserMessage,
    AssistantMessage,
    ToolResultMessage,
    CustomMessage,
    encode_messages,
    decode_messages,
    message_to_dict,
    message_from_dict,
    validate_history,
)
from .provider import ModelRequest, ModelEvent, Provider, set_default_stream_fn
from .lowlevel import (
    AgentContext,
    AgentLoopConfig,
    AgentEventStream,
    agent_loop,
    agent_loop_continue,
    run_agent_loop,
    run_agent_loop_continue,
)
from .proxy import ProxyProvider, stream_proxy
from .testing import ScriptedProvider
from .function_tools import tool
from .sync import LoopPortal, run_sync
from .tasks import TaskScope
from .features import FEATURES, require_features
from .recovery import (
    is_context_overflow,
    is_recoverable_length,
    is_retryable_error,
    retry_delay,
)
from .tools import (
    Tool,
    ToolContext,
    ToolExecutor,
    ToolResult,
    ToolResultUpdate,
    ToolOutcome,
    run_tool_call,
)
from .transcript import (
    current_tools,
    current_system_message,
    current_system_prompt,
    render_system_update,
)
from .estimate import clamp_max_tokens_to_context, estimate_context_tokens

__all__ = [
    "ModelInfo",
    "ModelCatalog",
    "Agent",
    "ImageContent",
    "ThinkingContent",
    "set_default_stream_fn",
    "AgentContext",
    "AgentLoopConfig",
    "AgentEventStream",
    "agent_loop",
    "agent_loop_continue",
    "run_agent_loop",
    "run_agent_loop_continue",
    "ProxyProvider",
    "stream_proxy",
    "AgentStateView",
    "RunResult",
    "CancelToken",
    "PiError",
    "ConfigurationError",
    "MessageValidationError",
    "UnsupportedCapabilityError",
    "ProviderProtocolError",
    "AgentBusyError",
    "AgentClosedError",
    "InvalidContinuationError",
    "ToolOutcomeUnknownError",
    "CleanupTimeoutError",
    "SubscriptionError",
    "CandidateValidationError",
    "Event",
    "EventListener",
    "Unsubscribe",
    "EventQueue",
    "encode_event",
    "decode_event",
    "AgentConfigUpdate",
    "Hooks",
    "RunContext",
    "TurnUpdate",
    "RunLimits",
    "JsonValue",
    "Message",
    "TextContent",
    "ToolCall",
    "ToolDeclaration",
    "SystemMessage",
    "UserMessage",
    "AssistantMessage",
    "ToolResultMessage",
    "CustomMessage",
    "encode_messages",
    "decode_messages",
    "message_to_dict",
    "message_from_dict",
    "validate_history",
    "ModelRequest",
    "ModelEvent",
    "Provider",
    "ScriptedProvider",
    "Tool",
    "tool",
    "run_sync",
    "LoopPortal",
    "TaskScope",
    "FEATURES",
    "require_features",
    "is_context_overflow",
    "is_recoverable_length",
    "is_retryable_error",
    "retry_delay",
    "ToolContext",
    "ToolExecutor",
    "ToolResult",
    "ToolResultUpdate",
    "ToolOutcome",
    "run_tool_call",
    "current_tools",
    "current_system_message",
    "current_system_prompt",
    "render_system_update",
    "estimate_context_tokens",
    "clamp_max_tokens_to_context",
]
